# Nova gateway (Hetzner) - Primary gateway
[[gateways]]
public_key = "keys/public.nova.gw.pem"

[gateways.address]
hostname = "nova.locut.us:31337"

# Vega gateway (AWS) - Secondary gateway
[[gateways]]
public_key = "keys/public.vega.gw.pem"

[gateways.address]
hostname = "vega.locut.us:31337"
